import client from './client';

export const adminApi = {
  getDashboard: () => client.get('/admin/dashboard'),
  products: {
    list: () => client.get('/admin/products'),
    get: (id: number | string) => client.get(`/admin/products/${id}`),
    create: (data: unknown) => client.post('/admin/products', data),
    update: (id: number | string, data: unknown) => client.patch(`/admin/products/${id}`, data),
    delete: (id: number | string) => client.delete(`/admin/products/${id}`),
    variants: (productId: number | string) => client.get(`/admin/products/${productId}/variants`),
    createVariant: (productId: number | string, data: unknown) => client.post(`/admin/products/${productId}/variants`, data),
    updateVariant: (variantId: number | string, data: unknown) => client.patch(`/admin/variants/${variantId}`, data),
    deleteVariant: (variantId: number | string) => client.delete(`/admin/variants/${variantId}`),
    media: (productId: number | string) => client.get(`/admin/products/${productId}/media`),
    createMedia: (productId: number | string, data: unknown) => client.post(`/admin/products/${productId}/media`, data),
    updateMedia: (mediaId: number | string, data: unknown) => client.patch(`/admin/media/${mediaId}`, data),
    deleteMedia: (mediaId: number | string) => client.delete(`/admin/media/${mediaId}`),
  },
  orders: {
    list: () => client.get('/admin/orders'),
    get: (id: number | string) => client.get(`/admin/orders/${id}`),
    update: (id: number | string, data: unknown) => client.patch(`/admin/orders/${id}`, data),
    updateStatus: (id: number | string, status: string, notes?: string) => client.patch(`/admin/orders/${id}/status`, { status, notes }),
    reviewPayment: (id: number | string, data: unknown) => client.patch(`/admin/orders/${id}/payment-review`, data),
  },
  formulas: {
    list: () => client.get('/admin/formulas'),
    get: (id: number | string) => client.get(`/admin/formulas/${id}`),
    create: (data: unknown) => client.post('/admin/formulas', data),
    update: (id: number | string, data: unknown) => client.patch(`/admin/formulas/${id}`, data),
    delete: (id: number | string) => client.delete(`/admin/formulas/${id}`),
    items: (formulaId: number | string) => client.get(`/admin/formulas/${formulaId}/items`),
    createItem: (formulaId: number | string, data: unknown) => client.post(`/admin/formulas/${formulaId}/items`, data),
    updateItem: (id: number | string, data: unknown) => client.patch(`/admin/items/${id}`, data),
    deleteItem: (id: number | string) => client.delete(`/admin/items/${id}`),
  },
  batches: {
    list: () => client.get('/admin/batches'),
    get: (id: number | string) => client.get(`/admin/batches/${id}`),
    create: (data: unknown) => client.post('/admin/batches', data),
    update: (id: number | string, data: unknown) => client.patch(`/admin/batches/${id}`, data),
    delete: (id: number | string) => client.delete(`/admin/batches/${id}`),
  },
  inventory: {
    lowStock: () => client.get('/admin/inventory/low-stock'),
    movements: () => client.get('/admin/inventory/movements'),
    adjust: (data: unknown) => client.post('/admin/inventory/adjustments', data),
  },
  customers: {
    list: () => client.get('/admin/customers'),
    get: (id: number | string) => client.get(`/admin/customers/${id}`),
    create: (data: unknown) => client.post('/admin/customers', data),
    update: (id: number | string, data: unknown) => client.patch(`/admin/customers/${id}`, data),
    delete: (id: number | string) => client.delete(`/admin/customers/${id}`),
  },
  coupons: {
    list: () => client.get('/admin/coupons'),
    create: (data: unknown) => client.post('/admin/coupons', data),
    update: (id: number | string, data: unknown) => client.patch(`/admin/coupons/${id}`, data),
    delete: (id: number | string) => client.delete(`/admin/coupons/${id}`),
  },
  pages: {
    list: () => client.get('/admin/pages'),
    create: (data: unknown) => client.post('/admin/pages', data),
    update: (id: number | string, data: unknown) => client.patch(`/admin/pages/${id}`, data),
    delete: (id: number | string) => client.delete(`/admin/pages/${id}`),
    sections: (pageId: number | string) => client.get(`/admin/pages/${pageId}/sections`),
    createSection: (pageId: number | string, data: unknown) => client.post(`/admin/pages/${pageId}/sections`, data),
    updateSection: (id: number | string, data: unknown) => client.patch(`/admin/sections/${id}`, data),
    deleteSection: (id: number | string) => client.delete(`/admin/sections/${id}`),
  },
  settings: {
    list: () => client.get('/admin/settings'),
    create: (data: unknown) => client.post('/admin/settings', data),
    update: (id: number | string, data: unknown) => client.patch(`/admin/settings/${id}`, data),
    delete: (id: number | string) => client.delete(`/admin/settings/${id}`),
  },
  quality: {
    list: () => client.get('/admin/quality-checks'),
    create: (data: unknown) => client.post('/admin/quality-checks', data),
    update: (id: number | string, data: unknown) => client.patch(`/admin/quality-checks/${id}`, data),
    delete: (id: number | string) => client.delete(`/admin/quality-checks/${id}`),
  },
  ingredients: {
    list: () => client.get('/admin/ingredients'),
    create: (data: unknown) => client.post('/admin/ingredients', data),
    update: (id: number | string, data: unknown) => client.patch(`/admin/ingredients/${id}`, data),
    delete: (id: number | string) => client.delete(`/admin/ingredients/${id}`),
  },
};
