import type { Locale } from '../context/LocaleContext';

const pageBody = {
  about: {
    ar: {
      hero: 'نفَس هو حضور محلي فاخر صُمّم ليكون واضحًا في الإحساس وسهلًا في الاختيار.',
      sections: [
        {
          title: 'فكرة نفَس',
          body: 'نصمم تجربة شراء العطر حول ما يهم فعلًا: صورة واضحة للعبوة، وصف صادق للرائحة، وأحجام مفهومة من أول نظرة.',
        },
        {
          title: 'فلسفة الحضور',
          body: 'نؤمن أن العطر لا يحتاج إلى مبالغة. يحتاج إلى افتتاحية دقيقة، قلب متوازن، وأثر يكمّل حضور صاحبه.',
        },
        {
          title: 'واجهة عربية أولًا',
          body: 'كل خطوة في المتجر مبنية لتخدم المتسوق العربي بشكل طبيعي، مع دعم إنجليزي متوازن لمن يفضّله.',
        },
      ],
    },
    en: {
      hero: 'Nafas is a local luxury fragrance storefront designed to feel clear, calm, and worth trusting.',
      sections: [
        {
          title: 'The idea behind Nafas',
          body: 'We shape fragrance shopping around what matters most: a clear bottle view, an honest scent description, and sizes that make sense at first glance.',
        },
        {
          title: 'A philosophy of presence',
          body: 'We believe fragrance does not need exaggeration. It needs a deliberate opening, a balanced heart, and a trail that completes the person wearing it.',
        },
        {
          title: 'Arabic-first by design',
          body: 'The entire storefront is built to feel natural in Arabic first, with a balanced English experience alongside it.',
        },
      ],
    },
  },
  faq: {
    ar: {
      hero: 'إجابات واضحة وسريعة حتى تصل لقرارك بثقة.',
      sections: [
        {
          title: 'هل يمكنني اختيار حجم مناسب للتجربة؟',
          body: 'نعم. إذا كان العطر جديدًا عليك، ابدأ بحجم أصغر أو اختر تستر حين يتوفر ضمن الصفحة أو الفلاتر.',
        },
        {
          title: 'كيف أعرف طبيعة العطر بسرعة؟',
          body: 'كل صفحة منتج تعرض الشخصية، القصة العطرية، النوتات، الموسم، الفوحان، والثبات بشكل مختصر وواضح.',
        },
        {
          title: 'متى يتم تأكيد الطلب؟',
          body: 'بعد إتمام الطلب ستظهر لك صفحة التأكيد، ثم تتم مراجعة الطلب والتواصل عند الحاجة عبر قناة الدعم المتاحة.',
        },
      ],
    },
    en: {
      hero: 'Clear, fast answers so you can decide with confidence.',
      sections: [
        {
          title: 'Can I start with a smaller size?',
          body: 'Yes. If the fragrance is new to you, begin with a smaller size or choose a tester whenever that option is available.',
        },
        {
          title: 'How do I understand a fragrance quickly?',
          body: 'Each product page shows the personality, scent story, notes, season, projection, and longevity in a short readable format.',
        },
        {
          title: 'When is my order confirmed?',
          body: 'After checkout you will see an order confirmation page, then the order is reviewed and support can follow up if needed.',
        },
      ],
    },
  },
  'privacy-policy': {
    ar: {
      hero: 'نحترم بياناتك ونستخدمها فقط لتشغيل الطلبات وتحسين التجربة.',
      sections: [
        {
          title: 'البيانات التي نجمعها',
          body: 'الاسم، رقم الهاتف، البريد الإلكتروني الاختياري، وعنوان التوصيل تُستخدم لتنفيذ الطلب والتواصل المرتبط به.',
        },
        {
          title: 'استخدام البيانات',
          body: 'نستخدم البيانات لتأكيد الطلبات، التوصيل، والمتابعة الأساسية فقط. لا ينبغي اعتبار هذه الصفحة بديلاً عن مراجعة قانونية رسمية قبل الإطلاق التجاري.',
        },
      ],
    },
    en: {
      hero: 'We respect your data and use it only to operate orders and improve the buying experience.',
      sections: [
        {
          title: 'What we collect',
          body: 'Name, phone number, optional email, and delivery address are used to process the order and communicate about it.',
        },
        {
          title: 'How it is used',
          body: 'We use customer details for order confirmation, delivery, and essential support. This page should still be reviewed legally before commercial launch.',
        },
      ],
    },
  },
  quality: {
    ar: {
      hero: 'الجودة هنا تظهر في التوازن، التشطيب، ووضوح الاختيار من أول زيارة.',
      sections: [
        {
          title: 'توازن عطري',
          body: 'كل عطر يقدَّم بوصف واضح يشرح الانطباع والمزاج والاتجاه العام للرائحة دون وعود مبالغ فيها.',
        },
        {
          title: 'تشطيب العبوة',
          body: 'الاهتمام بالصورة والعبوة جزء من التجربة: زجاج واضح، تفاصيل مقروءة، وإحساس بصري متماسك عبر كامل الواجهة.',
        },
        {
          title: 'شراء أسهل',
          body: 'الأحجام، الأسعار، والتوافر تظهر بوضوح لتقليل التردد وتبسيط القرار.',
        },
      ],
    },
    en: {
      hero: 'Quality here shows up in balance, finishing, and clear product decisions from the first visit.',
      sections: [
        {
          title: 'Balanced fragrance stories',
          body: 'Each scent is described with honest language about mood, direction, and presence without exaggerated claims.',
        },
        {
          title: 'Bottle and visual finishing',
          body: 'Bottle clarity, readable details, and a cohesive visual language are treated as part of the luxury experience.',
        },
        {
          title: 'An easier buying path',
          body: 'Sizes, pricing, and availability stay visible so the user can decide with less friction.',
        },
      ],
    },
  },
  'return-policy': {
    ar: {
      hero: 'سياسة واضحة تمنحك ثقة أكبر قبل إتمام الطلب.',
      sections: [
        {
          title: 'قبل الاستلام',
          body: 'يمكن مراجعة الطلب أو تعديله قبل بدء التجهيز النهائي بحسب حالة الطلب وسياسة التشغيل.',
        },
        {
          title: 'بعد الاستلام',
          body: 'أي سياسة استرجاع أو استبدال فعلية يجب تأكيدها قانونيًا وتشغيليًا من جانب العلامة قبل النشر العام النهائي.',
        },
      ],
    },
    en: {
      hero: 'A clear return policy builds confidence before checkout.',
      sections: [
        {
          title: 'Before delivery',
          body: 'Orders can typically be reviewed or updated before final preparation, depending on operational policy.',
        },
        {
          title: 'After delivery',
          body: 'Any final return or exchange terms should still be reviewed and confirmed by the business before public launch.',
        },
      ],
    },
  },
  terms: {
    ar: {
      hero: 'شروط استخدام بسيطة وواضحة لتجربة شراء موثوقة.',
      sections: [
        {
          title: 'استخدام المتجر',
          body: 'يُفترض استخدام المتجر لشراء المنتجات المتاحة أو مراجعة المحتوى المرتبط بها وفق القوانين المحلية السارية.',
        },
        {
          title: 'توفر المنتجات',
          body: 'قد تختلف الأسعار أو التوافر بحسب المخزون الفعلي، ويظل عرض الحالة داخل الصفحة هو المرجع الأقرب للمستخدم.',
        },
      ],
    },
    en: {
      hero: 'Simple terms for a more trustworthy buying experience.',
      sections: [
        {
          title: 'Using the storefront',
          body: 'The storefront is intended for reviewing and ordering available products in accordance with local laws and brand policy.',
        },
        {
          title: 'Availability and pricing',
          body: 'Availability and pricing may change with real inventory, and the product page remains the clearest reference for the shopper.',
        },
      ],
    },
  },
} as const;

export const publicCopy = {
  ar: {
    account: {
      detailTitle: 'تفاصيل الطلب',
      emptyOrdersDescription: 'بمجرد إتمام أول طلب، ستظهر تفاصيله هنا مع الحالة والرقم المرجعي.',
      emptyOrdersTitle: 'لا توجد طلبات بعد',
      heading: 'لوحة الحساب',
      intro: 'واجهة هادئة تحفظ بياناتك وطلباتك بشكل واضح وسهل المتابعة.',
      ordersCta: 'عرض الطلبات',
      ordersDescription: 'راجع الحالة، الرقم المرجعي، وتفاصيل كل طلبية في واجهة واضحة على الموبايل وسطح المكتب.',
      ordersTitle: 'طلباتي',
      profileDescription: 'بيانات الحساب الأساسية محفوظة هنا لتسهيل المتابعة لاحقًا.',
      profileTitle: 'بيانات الحساب',
      welcome: 'أهلًا بك في نفَس',
    },
    auth: {
      email: 'البريد الإلكتروني',
      loginBody: 'سجّل الدخول لحفظ طلباتك، متابعة حالتها، ودمج السلة الحالية مع حسابك.',
      loginEyebrow: 'مرحبًا بعودتك',
      loginTitle: 'تسجيل الدخول إلى نفَس',
      loginSubmit: 'دخول',
      loginSubmitting: 'جارِ الدخول...',
      name: 'الاسم',
      noAccount: 'ليس لديك حساب؟',
      password: 'كلمة المرور',
      registerBody: 'أنشئ حسابًا لتبقى تجربة الشراء، الطلبات، والمتابعة متصلة في مكان واحد.',
      registerEyebrow: 'ابدأ رحلتك',
      registerTitle: 'أنشئ حسابك في نفَس',
      registerSubmit: 'إنشاء الحساب',
      registerSubmitting: 'جارِ إنشاء الحساب...',
      signInInstead: 'لديك حساب بالفعل؟',
      signInLink: 'سجّل الدخول',
      signUpLink: 'أنشئ حسابًا جديدًا',
    },
    cart: {
      continueShopping: 'تابع التسوق',
      emptyDescription: 'ابدأ من المجموعة، ثم عد هنا حين تجد العطر الذي يشبه حضورك.',
      emptyTitle: 'السلة ما زالت فارغة',
      openDrawer: 'افتح السلة السريعة',
      quickTitle: 'سلة نفَس',
      remove: 'إزالة',
      shipping: 'يُحسب عند تأكيد الطلب',
      summaryBody: 'مراجعة واضحة وهادئة قبل الانتقال إلى الدفع.',
      summaryTitle: 'ملخص الطلب',
      title: 'سلة الشراء',
      total: 'الإجمالي التقديري',
      viewCart: 'صفحة السلة الكاملة',
    },
    checkout: {
      address: 'العنوان',
      city: 'المدينة',
      cod: 'الدفع عند الاستلام',
      confirm: 'تأكيد الطلب',
      confirming: 'جارِ تأكيد الطلب...',
      customer: 'بيانات العميل',
      delivery: 'عنوان التوصيل',
      email: 'البريد الإلكتروني (اختياري)',
      emptyMessage: 'أضف منتجًا واحدًا على الأقل قبل إتمام الطلب.',
      emptyTitle: 'السلة فارغة',
      governorate: 'المحافظة',
      heading: 'إتمام الطلب',
      name: 'الاسم الكامل',
      notes: 'ملاحظات التوصيل',
      payment: 'طريقة الدفع',
      phone: 'رقم الهاتف',
      review: 'مراجعة الطلب',
      reviewHint: 'راجع العناصر والكمية والعنوان قبل تأكيد الطلب.',
      subtitle: 'حقول مريحة، خطوات واضحة، وملخص نهائي يمنحك الثقة قبل التأكيد.',
      total: 'الإجمالي النهائي',
    },
    common: {
      addToCart: 'أضف للسلة',
      addedToCart: 'تمت الإضافة',
      all: 'الكل',
      close: 'إغلاق',
      continue: 'استمرار',
      discover: 'اكتشف العطور',
      empty: 'لا توجد عناصر',
      error: 'حدث خطأ غير متوقع',
      loading: 'جارِ التحميل...',
      notes: 'النوتات',
      orderNow: 'اطلب الآن',
      outOfStock: 'نفد',
      quantity: 'الكمية',
      shopNow: 'اذهب إلى المتجر',
      size: 'الحجم',
      soldOut: 'غير متوفر الآن',
      stock: 'التوفر',
      viewProduct: 'عرض المنتج',
      whatsapp: 'اطلب عبر واتساب',
    },
    footer: {
      body: 'نفَس يقدّم تجربة شراء عطر عربية أولًا: صور واضحة، خطوات بسيطة، وحضور بصري هادئ لكنه فاخر.',
      collections: 'المجموعة',
      contactLine: 'واتساب للطلب والدعم',
      help: 'المساعدة',
      legal: 'هذه الواجهة مصممة لتجعل اكتشاف العطر وطلبه أسهل وأكثر ثقة.',
      pages: 'نفَس',
      rights: 'Nafas. جميع الحقوق محفوظة.',
      supportLine: 'صناعة محلية بروح راقية وتجربة شراء واضحة.',
    },
    home: {
      collectionBody: 'ثمانية توقيعات عطرية بحضور واضح وصورة حقيقية للعبوة، لتعرف العطر أسرع وتختار بثقة أكبر.',
      collectionTitle: 'المجموعة المميّزة',
      ctaBody: 'حين تعرف أي نفَس يشبهك، اجعل الطلب التالي أسرع وأوضح.',
      ctaTitle: 'اختر نفَسك الآن',
      discoveryBody: 'ابدأ بتستر أو حجم أقرب للتجربة، ثم قرر بثقة أكبر أي زجاجة تناسب حضورك.',
      discoveryPrimary: 'اختار نفَسك',
      discoverySecondary: 'تسوّق المجموعة',
      discoveryTitle: 'تجربة أولى أهدأ',
      heroBody: 'قصة عطرية تبدأ من السكون وتترك أثرًا. زجاجة واضحة، مشهد سينمائي، وخطوتا شراء فقط فوق الطيّة.',
      heroEyebrow: 'نفَس — جوهر الحضور',
      heroPrimary: 'اكتشف العطور',
      heroSecondary: 'اطلب الآن',
      heroTitle: 'نفَس... أول رشة تكمل حضورك',
      journeyBody: 'مشهد واقعي يحكي لحظة العطر من الزجاجة المغلقة حتى أول نفَس يترك أثره. بدون خدع رخيصة، فقط صورة وصوت وحركة تخدم المنتج.',
      journeyTitle: 'طقس عطري يتحرك مع تمريرك',
      promiseBody: 'الجودة هنا تظهر في التوازن، التشطيب، وهدوء مسار الشراء من أول زيارة إلى آخر خطوة.',
      promiseCards: [
        {
          body: 'أثر واضح ومصقول يبقى حاضرًا دون مبالغة أو وعود غير واقعية.',
          title: 'ثبات أنيق',
        },
        {
          body: 'زجاجة واضحة، صورة صادقة، وتفاصيل مقروءة تجعل المنتج مفهومًا خلال ثوانٍ.',
          title: 'رؤية أوضح',
        },
        {
          body: 'فلاتر بسيطة، أحجام مفهومة، وسلة جانبية تجعل القرار أسرع وأهدأ.',
          title: 'شراء أسهل',
        },
      ],
      promiseTitle: 'لماذا يبقى نفَس في الذاكرة',
      scroll: 'مرّر لتتنفس القصة',
    },
    journey: {
      cta: 'اختار نفَسك',
      fallbackLabel: 'إذا تعذّر تشغيل الفيديو، تبقى الرحلة واضحة عبر الملصق والمراحل الست.',
      intro: 'رؤية عطرية صادقة تبدأ من زجاجة ساكنة وتنتهي بأول نفَس يترك أثره. التمرير هنا يخدم المنتج، لا يستعرض الحيلة.',
      kicker: 'طقس العطر',
      loadingLabel: 'جارِ تجهيز التسلسل السينمائي...',
      title: 'رحلة عطرية تتحرك مع تمريرك',
      stages: [
        {
          body: 'الزجاجة مغلقة تمامًا. يبدأ الحضور قبل أول رشة.',
          title: 'البداية الهادئة',
        },
        {
          body: 'دوران مقصود يكشف الكتلة والزجاج واللمعة من كل زاوية.',
          title: 'الحضور من كل زاوية',
        },
        {
          body: 'يرتفع الغطاء بهدوء لتبدأ لحظة الكشف دون مبالغة.',
          title: 'لحظة الكشف',
        },
        {
          body: 'رشة واحدة محسوبة تكفي لتعلن البداية.',
          title: 'أول نفَس',
        },
        {
          body: 'الدوران الثاني يترك الإحساس يتحرك معك لا حولك فقط.',
          title: 'الأثر يتحرك معك',
        },
        {
          body: 'تغلق الزجاجة من جديد، ويصبح القرار النهائي لك.',
          title: 'اختار نفَسك',
        },
      ],
    },
    nav: {
      account: 'الحساب',
      links: [
        { label: 'الرئيسية', to: '/' },
        { label: 'المتجر', to: '/shop' },
        { label: 'عن نفَس', to: '/about' },
        { label: 'الجودة', to: '/quality' },
        { label: 'الأسئلة الشائعة', to: '/faq' },
      ],
      menu: 'القائمة',
      tagline: 'أول رشة تكمل حضورك',
    },
    order: {
      continueShopping: 'تابع التسوق',
      lookupBody: 'إذا فتحت الصفحة من جهاز آخر، أدخل رقم الهاتف المستخدم أثناء الطلب لعرض التفاصيل.',
      lookupButton: 'عرض الطلب',
      lookupPlaceholder: 'رقم الهاتف المستخدم في الطلب',
      lookupTitle: 'ابحث عن طلبك بأمان',
      receivedBody: 'تم استلام طلبك. احتفظ برقم الطلب للمتابعة السريعة أو التواصل عبر واتساب.',
      receivedTitle: 'تم استلام طلبك بنجاح',
      support: 'واتساب الدعم',
      summaryTitle: 'ملخص الطلب',
    },
    product: {
      chooseSize: 'اختر الحجم',
      descriptionTitle: 'القصة العطرية',
      detailsTitle: 'كل ما تحتاجه لتقرر خلال ثوانٍ',
      fallbackStory: 'حضور مصقول يبدأ بهدوء ويترك أثرًا ثابتًا.',
      mediaLabel: 'المنتج',
      moreLikeThis: 'قد يعجبك أيضًا',
      mood: 'المود',
      notes: 'النوتات',
      price: 'السعر',
      projection: 'الفوحان',
      relatedTitle: 'عطور قريبة من مزاجك',
      season: 'الموسم',
      sizes: 'الأحجام',
      strength: 'الانطباع',
      viewAll: 'استعرض المجموعة',
      whatsappBody: 'اسأل مباشرة عن التوفر أو اطلب عبر واتساب.',
    },
    shop: {
      emptyDescription: 'جرّب وصفًا عطريًا آخر أو بدّل الفلاتر للوصول لنتائج أقرب.',
      emptyTitle: 'لا توجد نتائج الآن',
      filters: {
        all: 'الكل',
        coffee: 'قهوة',
        fresh: 'فريش',
        gifts: 'هدايا',
        men: 'رجالي',
        musky: 'مسكي',
        testers: 'تسترات',
        women: 'حريمي',
        woody: 'خشبي',
      },
      searchPlaceholder: 'ابحث بالاسم أو المود أو الحجم',
      subtitle: 'اختَر عطرك من مجموعة نفَس',
      title: 'اكتشف العطور',
    },
  },
  en: {
    account: {
      detailTitle: 'Order details',
      emptyOrdersDescription: 'Once you complete your first order, it will appear here with its status and reference number.',
      emptyOrdersTitle: 'No orders yet',
      heading: 'Account',
      intro: 'A calm account area that keeps your details and orders easy to review.',
      ordersCta: 'View orders',
      ordersDescription: 'Track status, reference numbers, and each order in a layout that works on both mobile and desktop.',
      ordersTitle: 'My orders',
      profileDescription: 'Your basic account details stay here for easier follow-up later.',
      profileTitle: 'Profile',
      welcome: 'Welcome to Nafas',
    },
    auth: {
      email: 'Email',
      loginBody: 'Sign in to save your orders, track them, and merge the current cart with your account.',
      loginEyebrow: 'Welcome back',
      loginTitle: 'Sign in to Nafas',
      loginSubmit: 'Sign in',
      loginSubmitting: 'Signing in...',
      name: 'Name',
      noAccount: 'No account yet?',
      password: 'Password',
      registerBody: 'Create an account to keep your cart, orders, and follow-up connected in one place.',
      registerEyebrow: 'Start your journey',
      registerTitle: 'Create your Nafas account',
      registerSubmit: 'Create account',
      registerSubmitting: 'Creating account...',
      signInInstead: 'Already have an account?',
      signInLink: 'Sign in',
      signUpLink: 'Create one',
    },
    cart: {
      continueShopping: 'Continue shopping',
      emptyDescription: 'Start with the collection, then come back once you find the fragrance that fits your presence.',
      emptyTitle: 'Your cart is still empty',
      openDrawer: 'Open quick cart',
      quickTitle: 'Nafas cart',
      remove: 'Remove',
      shipping: 'Calculated at order confirmation',
      summaryBody: 'A calm, clear review before moving to payment.',
      summaryTitle: 'Order summary',
      title: 'Shopping cart',
      total: 'Estimated total',
      viewCart: 'Full cart page',
    },
    checkout: {
      address: 'Address',
      city: 'City',
      cod: 'Cash on delivery',
      confirm: 'Confirm order',
      confirming: 'Confirming order...',
      customer: 'Customer details',
      delivery: 'Delivery address',
      email: 'Email (optional)',
      emptyMessage: 'Add at least one item before checking out.',
      emptyTitle: 'Your cart is empty',
      governorate: 'Governorate',
      heading: 'Checkout',
      name: 'Full name',
      notes: 'Delivery notes',
      payment: 'Payment method',
      phone: 'Phone number',
      review: 'Order review',
      reviewHint: 'Review the items, quantity, and address before placing the order.',
      subtitle: 'Comfortable fields, clear steps, and a final summary before you place the order.',
      total: 'Final total',
    },
    common: {
      addToCart: 'Add to cart',
      addedToCart: 'Added',
      all: 'All',
      close: 'Close',
      continue: 'Continue',
      discover: 'Discover perfumes',
      empty: 'No items',
      error: 'Something went wrong',
      loading: 'Loading...',
      notes: 'Notes',
      orderNow: 'Order now',
      outOfStock: 'Sold out',
      quantity: 'Quantity',
      shopNow: 'Go to shop',
      size: 'Size',
      soldOut: 'Unavailable now',
      stock: 'Availability',
      viewProduct: 'View product',
      whatsapp: 'Order on WhatsApp',
    },
    footer: {
      body: 'Nafas offers an Arabic-first fragrance storefront with clear imagery, easier flows, and a quieter luxury feel.',
      collections: 'Collection',
      contactLine: 'WhatsApp for orders and support',
      help: 'Help',
      legal: 'This interface is designed to make fragrance discovery and ordering feel calmer and more trustworthy.',
      pages: 'Nafas',
      rights: 'Nafas. All rights reserved.',
      supportLine: 'Locally made, visually refined, and easier to shop.',
    },
    home: {
      collectionBody: 'Eight fragrance signatures with a real bottle view, faster scent understanding, and a more premium path to purchase.',
      collectionTitle: 'Signature collection',
      ctaBody: 'Once you know which Nafas fits you, let the next order feel faster and clearer.',
      ctaTitle: 'Choose your breath now',
      discoveryBody: 'Start with a tester or a smaller size, then decide with more confidence which bottle fits your presence.',
      discoveryPrimary: 'Choose your breath',
      discoverySecondary: 'Shop the collection',
      discoveryTitle: 'A softer first discovery',
      heroBody: 'A fragrance story that starts quietly and leaves a trail. Clear bottle imagery, cinematic mood, and only two actions above the fold.',
      heroEyebrow: 'Nafas — the essence of presence',
      heroPrimary: 'Discover perfumes',
      heroSecondary: 'Order now',
      heroTitle: 'Nafas — the first spray that completes your presence',
      journeyBody: 'A realistic fragrance sequence that moves from a sealed bottle to the first breath. No cheap tricks, only media that serves the product.',
      journeyTitle: 'A fragrance ritual guided by your scroll',
      promiseBody: 'Quality shows up here in balance, finishing, and a quieter path from discovery to checkout.',
      promiseCards: [
        {
          body: 'A polished trail that stays present without exaggerated claims or clutter.',
          title: 'Elegant longevity',
        },
        {
          body: 'Clear bottle imagery and readable details help the user understand the product quickly.',
          title: 'Clearer product vision',
        },
        {
          body: 'Simpler filters, understandable sizes, and a side cart that keeps the flow easy.',
          title: 'An easier buying path',
        },
      ],
      promiseTitle: 'Why Nafas stays with you',
      scroll: 'Scroll to breathe the story',
    },
    journey: {
      cta: 'Choose your breath',
      fallbackLabel: 'If the video cannot play, the poster and six stages still carry the ritual clearly.',
      intro: 'A truthful fragrance sequence that begins with a still bottle and ends with the first breath leaving its trail. The scroll serves the product, not the gimmick.',
      kicker: 'Fragrance ritual',
      loadingLabel: 'Preparing the cinematic sequence...',
      title: 'A fragrance journey guided by your scroll',
      stages: [
        {
          body: 'The bottle stays fully closed. Presence begins before the first spray.',
          title: 'The Quiet Beginning',
        },
        {
          body: 'A deliberate rotation reveals the weight, glass, and glow from every side.',
          title: 'Presence From Every Angle',
        },
        {
          body: 'The cap lifts softly so the reveal feels measured, not exaggerated.',
          title: 'The Reveal',
        },
        {
          body: 'One controlled spray is enough to announce the beginning.',
          title: 'The First Breath',
        },
        {
          body: 'The second rotation lets the aura move with you, not just around you.',
          title: 'The Trail Moves With You',
        },
        {
          body: 'The bottle closes again, leaving the final decision to you.',
          title: 'Choose Your Breath',
        },
      ],
    },
    nav: {
      account: 'Account',
      links: [
        { label: 'Home', to: '/' },
        { label: 'Shop', to: '/shop' },
        { label: 'About', to: '/about' },
        { label: 'Quality', to: '/quality' },
        { label: 'FAQ', to: '/faq' },
      ],
      menu: 'Menu',
      tagline: 'The first spray that completes your presence',
    },
    order: {
      continueShopping: 'Continue shopping',
      lookupBody: 'If you opened this page from another device, enter the phone number used for the order to load the details safely.',
      lookupButton: 'View order',
      lookupPlaceholder: 'Phone number used in the order',
      lookupTitle: 'Look up your order safely',
      receivedBody: 'Your order has been received. Keep the order number handy for quick follow-up or WhatsApp support.',
      receivedTitle: 'Your order has been received',
      support: 'WhatsApp support',
      summaryTitle: 'Order summary',
    },
    product: {
      chooseSize: 'Choose size',
      descriptionTitle: 'Fragrance story',
      detailsTitle: 'Everything you need to decide in seconds',
      fallbackStory: 'A polished presence that opens quietly and leaves a steady trail.',
      mediaLabel: 'Product',
      moreLikeThis: 'You may also like',
      mood: 'Mood',
      notes: 'Notes',
      price: 'Price',
      projection: 'Projection',
      relatedTitle: 'More scents near this mood',
      season: 'Season',
      sizes: 'Sizes',
      strength: 'Strength',
      viewAll: 'Browse collection',
      whatsappBody: 'Ask directly about availability or place the order through WhatsApp.',
    },
    shop: {
      emptyDescription: 'Try another scent description or adjust the filters to get closer results.',
      emptyTitle: 'No results right now',
      filters: {
        all: 'All',
        coffee: 'Coffee',
        fresh: 'Fresh',
        gifts: 'Gifts',
        men: 'Men',
        musky: 'Musky',
        testers: 'Testers',
        women: 'Women',
        woody: 'Woody',
      },
      searchPlaceholder: 'Search by name, mood, or size',
      subtitle: 'Choose your scent from the Nafas collection',
      title: 'Discover perfumes',
    },
  },
} as const;

export function getPublicCopy(locale: Locale) {
  return publicCopy[locale];
}

export function getContentPageCopy(slug: string, locale: Locale) {
  const key = (slug in pageBody ? slug : 'about') as keyof typeof pageBody;
  return pageBody[key][locale];
}
